### ISSUE TITLE
Include GNU Make in docker image

### ISSUE THREAD

**Issue by andreasabel** [sumandoc/TeXLive-2017#5]
Thanks for this docker image!  I am using it on travis to build PDFs from LaTeX.  I often have my own Makefiles for compiling tex files.  It would be nice if `make` was included in your docker image.

https://travis-ci.org/andreasabel/ipl/builds/407213784
```
docker run -v /home/travis/build/andreasabel/ipl:/home -w /home sumdoc/texlive-2017  make -C notes
container_linux.go:265: starting container process caused "exec: \"make\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"make\": executable file not found in $PATH".
```

**Comment by sumandoc** [comment]
Glad you liked it ! 
The old 2017 image is now difficult to build with `gnu make`.
Hope you will like [2018 image](https://hub.docker.com/r/sumdoc/texlive-2018/) that includes `make` and does your job.
